title: Tonmoy Datta
description: Enthusiastic B.Sc. student in Electronics and Telecommunication Engineering at CUET with a focus on cybersecurity.
Committed to developing and applying technical skills in secure technology solutions.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
